// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PromptForLocalDBPath() {
  return window['go']['backend']['Backend']['PromptForLocalDBPath']();
}

export function SelectKobo(arg1) {
  return window['go']['backend']['Backend']['SelectKobo'](arg1);
}

export function DetectKobos() {
  return window['go']['backend']['Backend']['DetectKobos']();
}

export function ForwardToReadwise() {
  return window['go']['backend']['Backend']['ForwardToReadwise']();
}

export function GetBookmark() {
  return window['go']['backend']['Backend']['GetBookmark']();
}

export function GetContent() {
  return window['go']['backend']['Backend']['GetContent']();
}

export function GetSelectedKobo() {
  return window['go']['backend']['Backend']['GetSelectedKobo']();
}

export function GetSettings() {
  return window['go']['backend']['Backend']['GetSettings']();
}
