// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetSelectedKobo():Promise<backend.Kobo>;

export function SelectKobo(arg1:string):Promise<Error>;

export function PromptForLocalDBPath():Promise<Error>;

export function DetectKobos():Promise<Array<backend.Kobo>>;

export function ForwardToReadwise():Promise<number|Error>;

export function GetBookmark():Promise<backend.Bookmark>;

export function GetContent():Promise<backend.Content>;

export function GetSettings():Promise<backend.Settings>;

export function ListDeviceContentWithCovers():Promise<Array<backend.Book>|Error>;

export function LoadCoverAsBytes(arg1:backend.Content):Promise<string>;
