// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function BuildContentIndex(arg1:Array<backend.Content>):Promise<{[key: string]: backend.Content}>;

export function CountDeviceBookmarks():Promise<backend.HighlightCounts>;

export function ListDeviceBookmarks(arg1:boolean):Promise<Array<backend.Bookmark>>;

export function ListDeviceContent(arg1:boolean):Promise<Array<backend.Content>>;
