// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListDeviceContent() {
  return window['go']['backend']['Kobo']['ListDeviceContent']();
}

export function BuildContentIndex(arg1) {
  return window['go']['backend']['Kobo']['BuildContentIndex'](arg1);
}

export function CountDeviceBookmarks() {
  return window['go']['backend']['Kobo']['CountDeviceBookmarks']();
}

export function FindBookOnDevice(arg1) {
  return window['go']['backend']['Kobo']['FindBookOnDevice'](arg1);
}

export function ListBookmarksByID(arg1) {
  return window['go']['backend']['Kobo']['ListBookmarksByID'](arg1);
}

export function ListBooksOnDevice() {
  return window['go']['backend']['Kobo']['ListBooksOnDevice']();
}

export function ListDeviceBookmarks() {
  return window['go']['backend']['Kobo']['ListDeviceBookmarks']();
}
