// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function BuildContentIndex(arg1:Array<backend.Content>):Promise<{[key: string]: backend.Content}>;

export function CountDeviceBookmarks():Promise<number>;

export function FindBookOnDevice(arg1:string):Promise<backend.Content>;

export function ListBookmarksByID(arg1:string):Promise<Array<backend.Bookmark>>;

export function ListBooksOnDevice():Promise<Array<backend.Content>>;

export function ListDeviceBookmarks():Promise<Array<backend.Bookmark>>;

export function ListDeviceContent():Promise<Array<backend.Content>>;
