// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function SendBookmarks(arg1:backend.Response,arg2:string):Promise<number|Error>;

export function UploadCover(arg1:string,arg2:number,arg3:string):Promise<Error>;

export function CheckTokenValidity(arg1:string):Promise<Error>;

export function RetrieveUploadedBooks(arg1:string):Promise<backend.BookListResponse|Error>;
