// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckTokenValidity(arg1) {
  return window['go']['backend']['Readwise']['CheckTokenValidity'](arg1);
}

export function RetrieveUploadedBooks(arg1) {
  return window['go']['backend']['Readwise']['RetrieveUploadedBooks'](arg1);
}

export function SendBookmarks(arg1, arg2) {
  return window['go']['backend']['Readwise']['SendBookmarks'](arg1, arg2);
}

export function UploadCover(arg1, arg2, arg3) {
  return window['go']['backend']['Readwise']['UploadCover'](arg1, arg2, arg3);
}
