// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Save():Promise<void>;

export function SaveCoverUploading(arg1:boolean):Promise<void>;

export function SaveStoreHighlights(arg1:boolean):Promise<void>;

export function SaveToken(arg1:string):Promise<void>;
