// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveToken(arg1:string):Promise<Error>;

export function CheckReadwiseConfig():Promise<boolean>;

export function Save():Promise<Error>;

export function SaveCoverUploading(arg1:boolean):Promise<Error>;
