// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckReadwiseConfig() {
  return window['go']['backend']['Settings']['CheckReadwiseConfig']();
}

export function Save() {
  return window['go']['backend']['Settings']['Save']();
}

export function SaveCoverUploading(arg1) {
  return window['go']['backend']['Settings']['SaveCoverUploading'](arg1);
}

export function SaveToken(arg1) {
  return window['go']['backend']['Settings']['SaveToken'](arg1);
}
