// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {device} from '../models';
import {context} from '../models';
import {map[string]device} from '../models';

export function ListDeviceContent():Promise<Array<device.Content>|Error>;

export function SelectKobo(arg1:string):Promise<Error>;

export function CountDeviceBookmarks():Promise<number>;

export function FindBookOnDevice(arg1:string):Promise<device.Content|Error>;

export function ListDeviceBookmarks():Promise<Array<device.Bookmark>|Error>;

export function SetCoverUploadStatus(arg1:boolean):Promise<Error>;

export function SetReadwiseToken(arg1:string):Promise<Error>;

export function CheckReadwiseConfig():Promise<boolean>;

export function GetReadwiseToken():Promise<string>;

export function GetSelectedKobo():Promise<device.Kobo>;

export function GetCoverUploadStatus():Promise<boolean>;

export function PromptForLocalDBPath():Promise<Error>;

export function SetContext(arg1:context.Context):void;

export function CheckTokenValidity():Promise<Error>;

export function DetectKobos():Promise<Array<device.Kobo>>;

export function ForwardToReadwise():Promise<number|Error>;

export function BuildContentIndex(arg1:Array<device.Content>):Promise<map[string]device.Content>;
