// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListDeviceContent() {
  return window['go']['main']['KoboService']['ListDeviceContent']();
}

export function SelectKobo(arg1) {
  return window['go']['main']['KoboService']['SelectKobo'](arg1);
}

export function CountDeviceBookmarks() {
  return window['go']['main']['KoboService']['CountDeviceBookmarks']();
}

export function FindBookOnDevice(arg1) {
  return window['go']['main']['KoboService']['FindBookOnDevice'](arg1);
}

export function ListDeviceBookmarks() {
  return window['go']['main']['KoboService']['ListDeviceBookmarks']();
}

export function SetCoverUploadStatus(arg1) {
  return window['go']['main']['KoboService']['SetCoverUploadStatus'](arg1);
}

export function SetReadwiseToken(arg1) {
  return window['go']['main']['KoboService']['SetReadwiseToken'](arg1);
}

export function CheckReadwiseConfig() {
  return window['go']['main']['KoboService']['CheckReadwiseConfig']();
}

export function GetReadwiseToken() {
  return window['go']['main']['KoboService']['GetReadwiseToken']();
}

export function GetSelectedKobo() {
  return window['go']['main']['KoboService']['GetSelectedKobo']();
}

export function GetCoverUploadStatus() {
  return window['go']['main']['KoboService']['GetCoverUploadStatus']();
}

export function PromptForLocalDBPath() {
  return window['go']['main']['KoboService']['PromptForLocalDBPath']();
}

export function SetContext(arg1) {
  window['go']['main']['KoboService']['SetContext'](arg1);
}

export function CheckTokenValidity() {
  return window['go']['main']['KoboService']['CheckTokenValidity']();
}

export function DetectKobos() {
  return window['go']['main']['KoboService']['DetectKobos']();
}

export function ForwardToReadwise() {
  return window['go']['main']['KoboService']['ForwardToReadwise']();
}

export function BuildContentIndex(arg1) {
  return window['go']['main']['KoboService']['BuildContentIndex'](arg1);
}
